# Generated by Django 6.1 on 2026-08-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category_at_send', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='zones.zone')),
            ],
        ),
    ]
