# Generated by Django 6.1 on 2026-08-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_location', models.JSONField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('description', models.TextField(blank=True)),
                ('pothole_detected', models.BooleanField(blank=True, null=True)),
                ('pothole_confidence', models.FloatField(blank=True, null=True)),
                ('waterlogging_detected', models.BooleanField(blank=True, null=True)),
                ('waterlogging_confidence', models.FloatField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='zones.zone')),
            ],
        ),
    ]
