/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
      colors: {
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          light: "var(--primary-light)",
          text: "var(--primary-text)",
        },
        teal: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
          950: "#042f2e",
        },
        civic: {
          blue: "#2563EB",
          "blue-light": "#DBEAFE",
          "blue-dark": "#3B82F6",
          "blue-dark-light": "#93C5FD",
        },
        saffron: {
          DEFAULT: "#E8730A",
          hover: "#C95F06",
          light: "#FFEDD5",
          "dark-light": "#FDE68A",
        },
        surface: {
          "light-base": "#F8FAFC",
          "light-card": "#FFFFFF",
          "light-secondary": "#F1F5F9",
          "dark-base": "#0B1220",
          "dark-main": "#0F172A",
          "dark-card": "#111C2E",
          "dark-secondary": "#162235",
          "dark-hover": "#1E293B",
        },
        border: {
          "light-subtle": "#E2E8F0",
          "light-strong": "#CBD5E1",
          "dark-subtle": "#243244",
          "dark-strong": "#334155",
        },
        risk: {
          low: "#16A34A",
          "low-bg": "#DCFCE7",
          "low-text": "#166534",
          medium: "#EAB308",
          "medium-bg": "#FEF9C3",
          "medium-text": "#854D0E",
          high: "#F97316",
          "high-bg": "#FFEDD5",
          "high-text": "#9A3412",
          severe: "#DC2626",
          "severe-bg": "#FEE2E2",
          "severe-text": "#991B1B",
          sos: "#DC2626",
          "sos-bg": "#FEF2F2",
        },
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "20px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(15,23,42,0.08)",
      },
    },
  },
  plugins: [],
};
