# Generated by Django 6.1 on 2026-08-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.JSONField()),
                ('elevation_factor', models.FloatField()),
                ('drainage_capacity', models.FloatField()),
                ('dispatch_status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Dispatched', 'Dispatched'), ('Resolved', 'Resolved')], default='Unassigned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_intensity_mm', models.FloatField()),
                ('source', models.CharField(choices=[('imd_api', 'imd_api'), ('simulated', 'simulated')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='zones.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion_level', models.IntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_readings', to='zones.zone')),
            ],
        ),
    ]
