# Generated by Django 6.1 on 2026-08-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreading',
            name='source',
            field=models.CharField(choices=[('open_meteo', 'open_meteo'), ('imd_api', 'imd_api'), ('simulated', 'simulated')], max_length=20),
        ),
    ]
